---
- hosts: kube
  become: yes
  user: root
  gather_facts: no
  pre_tasks:

  - name: 'Atualizando repositorio'
    raw: 'apt update'

  - name: 'Instalando o atualizações'
    raw: 'apt upgrade -y '

  roles:
  - { role: install_k8s,	tags: ["install_k8s_role"]}

- hosts: k8s-master
  become: yes
  user: root
  roles:
  - { role: create_cluster,	tags: ["create_cluster_role"]}

- hosts: k8s-workers
  become: yes
  user: root
  roles:
  - { role: join_cluster,	tags: ["join_workers_role"]}

- hosts: k8s-master
  become: yes
  user: root
  roles:
  - { role: install_extras,	tags: ["extras"]}
