- name: Instalando CertManager NGINX Kubernetes.
  shell: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
  ignore_errors: true
  when: INSTALL_CERTMANAGER|bool
