- name: Install HELM
  unarchive:
    src: https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: True
    extra_opts:
      - --strip=1
      - --wildcards
      - '*/helm'
  when: INSTALL_HELM|bool

