---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: app3-certificate
  namespace: app3
spec:
  commonName: w0rm30.seg.br
  dnsNames:
    - app3.w0rm30.seg.br
  secretName: app3-secret 
  issuerRef:
    name: app3-issuer
    kind: Issuer
